
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deplyoment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: db-pv-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
      containers:
        - name: db
          image: postgres
          env:
            - name: POSTGRES_USER
              value: wordpress
            - name: POSTGRES_PASSWORD
              value: wordpress
            - name: POSTGRES_DB
              value: perfdata
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "128Mi"
              cpu: "128m"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: db-pv-storage

          ports:
            - containerPort: 5432
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
